using System;
using FluentMigrator;
using Migrations.Framework;
using FluentMigrator.SqlServer;

namespace Migrations
{
    [Migration(201807121113)]
    public class _201807121113_import_role_data : Migration
    {
        public override void Down()
        {
            Delete.FromTable(TableName.Role).AllRows();
        }

        public override void Up()
        {
            // This code was generated by executing the following script from the legacy database

            //select 'Insert.IntoTable(TableName.Role).WithIdentityInsert().Row(new { Id = '+ id + 
            //+ ', Name = "'+ Name + '"'
            //+'});'
            //from roles

            Insert.IntoTable(TableName.Role).WithIdentityInsert().Row(new { Id = 1, Name = "Client" });
            Insert.IntoTable(TableName.Role).WithIdentityInsert().Row(new { Id = 2, Name = "Moderator" });
        }
    }
}
