using System;
using FluentMigrator;
using Migrations.Framework;

namespace Migrations
{
    [Migration(201806211049)]
    public class _201806211049_adding_company_table : Migration
    {
        public override void Down()
        {            
            Delete.Table(TableName.Company);
        }

        public override void Up()
        {
            Create.Table(TableName.Company)
                  .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                  .WithColumn("Name").AsString().NotNullable()
                  .WithColumn("Url").AsString(200).Nullable()
                  .WithColumn("Email").AsString(300).Nullable()
                  .WithColumn("LogoUrl").AsString(500).Nullable()
                  .WithColumn("CreatedBy").AsInt32().Nullable()
                  .WithColumn("CreatedAt").AsDateTime().NotNullable().WithDefault(SystemMethods.CurrentUTCDateTime)
                  .WithColumn("DeletedAt").AsDateTime().Nullable()
                  .WithColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);

            ImportData();
        }

        public void ImportData()
        {
            // This code was generated by executing the following script from the legacy database

            //select 'Insert.IntoTable(TableName.Company).Row(new { name = "'+ companyName + '"'
            //+', CreatedAt = DateTime.Parse("2018-07-11")'
            //+', IsActive = true'
            //+ case when companyUrl is null then '' else +', Url = "' + CompanyUrl + '"' end
            //+ case when companyLogoUrl is null then '' else +', LogoUrl = "' + companyLogoUrl  + '"' end
            //+ case when companyEmail is null then '' else +', Email = "' + CompanyEmail  + '"' end
            //+'});'
            //from jobopportunities
            //where created > '2018-01-01'
            //group by companyName, companyUrl, companyEmail, CompanyLogoUrl
            
            Insert.IntoTable(TableName.Company).Row(new { name = "12digitos", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "johanprevot@hotmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Advanced Professional Solutions", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.apsdr.com/", Email = "vacantes@apsdr.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Adventures Digital Agency", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://adventures.do/contactanos/", Email = "paola@adventures.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Almacen.do", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://almacen.do", LogoUrl = "https://i.imgur.com/xcYtWV2.jpg", Email = "trabajos{elimina-esto}@almacen.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "AppLab", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.applab.do", Email = "emilio@applab.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Argentuminc, SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "jestevez@argentuminc.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Banco Caribe", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "gborda@bancocaribe.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Blue Coding LLC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.bluecoding.com", LogoUrl = "https://www.bluecoding.com/assets/logo-7b580550d1c3000870947217a3b5b012d9e2e5847fef80d89021bf20e55ec197.png", Email = "hr@bluecoding.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Caribbean Social Club", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "info@caribbeansocialclub.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "ChinolaCloud, S.R.L.", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.chinolacloud.com", Email = "jennifer.cox@chinolacloud.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Codemera", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://codemera.com/", Email = "wendy@codemera.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "CSS", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "franklinacastillo@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Deevo", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "kennytejadatpa@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "DEXTRA SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://dextra.com.do/", Email = "reclutamiento@dextra.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "DISOFT SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "jobs@disoft.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "DomiNET", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "jobs@dominet.net" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Edu-zone", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://edu-zone.org/es/", Email = "empleo@edu-zone.org" });
            Insert.IntoTable(TableName.Company).Row(new { name = "EgoProxyDR", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "contacto@egoproxydr.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "ERC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "NMontilla@ercbpo.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Excello Technology S.R.L", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://excellotech.com", LogoUrl = "http://excellotech.com/wp-content/uploads/2017/02/logo-excello-med-neg-cut_med.png", Email = "lmponfellis@excellotech.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Farmahorro", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://farmahorro.com.do", LogoUrl = "http://farmahorro.com.do/construccion/images/logo_farmahorro.png", Email = "it02@farmahorro.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Gabriel", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "reservation@ambaassadorshotel.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "GFR Media", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.gfrmedia.com", LogoUrl = "http://i.imgur.com/dxWshW2.png", Email = "empleosrd@gfrmedia.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Gregory Pilar", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "gregorypilar@outlook.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Grupo Read", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.gruporead.com/", Email = "imartinez@gruporead.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "HelpNet, LLC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.help-net.net", LogoUrl = "http://help-net.net/logo-small-square.png", Email = "hrdr@help-net.net" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Humano", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "empleos@humano.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Humfel comercial", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "luishumeauf@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Ideologic SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://ideologic.do", LogoUrl = "https://ideologic.do/wp-content/themes/ideologic/img/logo.png", Email = "touch@ideologic.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Industrias San Miguel", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "joenilson@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Informatik", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.isgwebsite.com", Email = "careers@isgwebsite.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Ingenio Consulting", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "ingenio.vacantes@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "InstaCarro.com", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://jobs.kenoby.com/instacarro", Email = "jobs@instacarro.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Lacs BPO", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://lacsbpo.com/", Email = "info@lacsbpo.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "MCTEKK, SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://mctekk.com.do", LogoUrl = "https://image.ibb.co/e6JYWa/Screen_Shot_2017_08_04_at_11_57_19_AM.png", Email = "empleos@mctekk.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "MTS Services", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "recruitment.multimediosvdp@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "NTD INGREDIENTES", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://ntdingredientes.com", LogoUrl = "http://ntdingredientes.com/images/site-layout/nt%20ingredietes.png", Email = "tic@ntdingredientes.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Ntech SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "ntechsrldo@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "NUÑEZ RETAIL INVESMENT CORP SRL.", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "ASISTENTELORIS@HOTMAIL.COM" });
            Insert.IntoTable(TableName.Company).Row(new { name = "OffShoring DR", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "hr@offshoringdr.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Orkapi", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://orkapitechnology.com/", LogoUrl = "http://orkapitechnology.com/images/orkapi%20logo-02.png", Email = "pablovidal@orkapi.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Outsourcing Solutions International, LLC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.alchavo.com", Email = "esanchez@osipr.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Overlogy SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://www.overlogy.net/", Email = "overlogyrd@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "PacketSoft", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.packetsoft.net/", Email = "vacantespacketsoft@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "PBC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "jobs@20boxme.org" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Prestige Media, SRL", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, LogoUrl = "https://imgur.com/W0Wh9Sx", Email = "talents@prestigemedia.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Procuraduria General de la Republica", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.pgr.gob.do/", Email = "procuraduria.sitioweb@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Publicitaria interamerica, S.R.L", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://mullenloweinteramerica.com", LogoUrl = "http://lowe-interamerica.com/Logo_MullenLowe.png", Email = "rrhh@mullenloweinteramerica.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Rivera Rivera LLC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "franciscoj.riverag@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "SBIT LLc", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "support@sbit.co" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Scopic Software", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://scopicsoftware.com/", Email = "jobs@scopicsoftware.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Shopmundo", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.shopmundo.com/", Email = "d.morillo@shopmundo.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Sistemas Integrados de Informática", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://www.sii.com.do/", LogoUrl = "http://www.sii.com.do/media/1318/logo-sii.png", Email = "info@sii.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Slash Mine, LLC", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://slashmine.com", LogoUrl = "https://slashmine.com/images/slashSign.png", Email = "hr@slashmine.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Soluciones GBH", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "http://gbh.com.do/empleos", LogoUrl = "http://gbh.com.do/wp-content/uploads/2015/04/gbh-icon.png", Email = "gestionhumana@gbh.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Stagewood", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "cguzman@stagewood.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Synergies First", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "ecruz@synergiesfirst.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Vikcloud Solutions Srl", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "email.gravina@gmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Visa Ahora AV", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "trinidadcarlos@hotmail.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Viva", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "cmdelacruz@viva.com.do" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Vivial Inc.", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://vivial.net/", Email = "kguzman@vivial.net" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Webranx", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Email = "julio@webranx.com" });
            Insert.IntoTable(TableName.Company).Row(new { name = "Xolutech", CreatedAt = DateTime.Parse("2018-07-11"), IsActive = true, Url = "https://xolutech.com/", Email = "info@xolutech.com" });        }
    }
}
