using System;
using FluentMigrator;
using Domain;
using Migrations.Framework;

namespace Migrations
{
    [Migration(201807041319)]
    public class _201807041319_adding_location_table : Migration
    {
        public override void Down()
        {
            Delete.Table(TableName.Location);
        }

        public override void Up()
        {
            Create.Table(TableName.Location)
                  .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                  .WithColumn("PlaceId").AsString().NotNullable()
                  .WithColumn("Name").AsString().NotNullable()
                  .WithColumn("Latitude").AsString().NotNullable()
                  .WithColumn("Longitude").AsString().NotNullable()
                  .WithColumn("IsActive").AsString().NotNullable().WithDefaultValue(true)
                  .WithColumn("CreatedAt").AsString().NotNullable()
                  .WithColumn("DeletedAt").AsString().Nullable().WithDefault(SystemMethods.CurrentDateTime);


            ImportData();
        }

        private void ImportData()
        {
            // This code was generated by executing the following script from the legacy database

            //select distinct 'Insert.IntoTable(TableName.Location).Row(new Location { Id = '+ cast(l.id as varchar(5))
            //+', PlaceId = "' + cast(l.PlaceId as varchar(5)) + '"'
            //+', Name = "' + l.Name + '"'
            //+', Latitude =' + l.Latitude +
            //+', Longitude =' + l.Longitude+'});'
            //from jobopportunitylocations l
            //join JobOpportunities j on j.JobOpportunityLocationId = l.Id
            //where j.created > '2018-01-01'

            Insert.IntoTable(TableName.Location).Row(new Location { Id = 571, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 572, PlaceId = "ChIJv", Name = "Santo Domingo, República Dominicana", Latitude = 18.5261268, Longitude = -69.8835651 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 573, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 574, PlaceId = "ChIJv", Name = "Santo Domingo, República Dominicana", Latitude = 18.5261268, Longitude = -69.8835651 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 575, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 576, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 577, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 578, PlaceId = "ChIJT", Name = "Santiago, Dominican Republic", Latitude = 19.45409, Longitude = -70.69220250000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 579, PlaceId = "ChIJC", Name = "La Vega, República Dominicana", Latitude = 19.2211554, Longitude = -70.52887529999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 580, PlaceId = "ChIJC", Name = "La Vega, República Dominicana", Latitude = 19.2211554, Longitude = -70.52887529999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 581, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 582, PlaceId = "ChIJC", Name = "La Vega, República Dominicana", Latitude = 19.2211554, Longitude = -70.52887529999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 583, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 584, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 585, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 586, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 587, PlaceId = "ChIJ-", Name = "Puerto Rico", Latitude = 18.220833, Longitude = -66.590149 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 588, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 591, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 592, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 593, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 594, PlaceId = "ChIJs", Name = "Santo Domingo Province, Dominican Republic", Latitude = 18.51042529999999, Longitude = -69.84040540000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 595, PlaceId = "ChIJ9", Name = "Dominican Republic", Latitude = 18.735693, Longitude = -70.16265099999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 596, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 597, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 598, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 599, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 600, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 601, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 602, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 603, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 604, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 605, PlaceId = "ChIJq", Name = "Santo Domingo, Distrito Nacional, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 606, PlaceId = "ChIJn", Name = "Santiago, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 607, PlaceId = "ChIJn", Name = "Santiago, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 608, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 609, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 612, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 613, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 614, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 615, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 616, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 617, PlaceId = "ChIJd", Name = "Puerto Plata, Dominican Republic", Latitude = 19.7807686, Longitude = -70.68710909999999 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 618, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 619, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 620, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 621, PlaceId = "ChIJn", Name = "Santiago, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 622, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 623, PlaceId = "ChIJE", Name = "Los Alcarrizos, Santo Domingo, República Dominicana", Latitude = 18.5241872, Longitude = -70.02054040000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 624, PlaceId = "ChIJE", Name = "Los Alcarrizos, Santo Domingo, República Dominicana", Latitude = 18.5241872, Longitude = -70.02054040000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 625, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 626, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 627, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 628, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 629, PlaceId = "ChIJV", Name = "Santo Domingo Este, República Dominicana", Latitude = 18.505583, Longitude = -69.80017620000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 630, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 631, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 632, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 633, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 634, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 635, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 636, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 637, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 638, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 639, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 640, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 641, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 642, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 643, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 644, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 645, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 646, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 647, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 648, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 649, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 651, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 652, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 653, PlaceId = "ChIJE", Name = "Miami, FL, USA", Latitude = 25.7616798, Longitude = -80.19179020000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 654, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 655, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 656, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 657, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 658, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 659, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 660, PlaceId = "ChIJV", Name = "Santo Domingo Este, Dominican Republic", Latitude = 18.505583, Longitude = -69.80017620000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 661, PlaceId = "ChIJq", Name = "República Dominicana, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 662, PlaceId = "ChIJd", Name = "Orlando, FL, USA", Latitude = 28.5383355, Longitude = -81.37923649999999 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 663, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 664, PlaceId = "ChIJ9", Name = "Dominican Republic", Latitude = 18.735693, Longitude = -70.16265099999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 665, PlaceId = "ChIJ9", Name = "Dominican Republic", Latitude = 18.735693, Longitude = -70.16265099999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 666, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 667, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 668, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 669, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 670, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 671, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 672, PlaceId = "ChIJ9", Name = "Dominican Republic", Latitude = 18.735693, Longitude = -70.16265099999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 674, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 675, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 676, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 677, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 678, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 679, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 680, PlaceId = "ChIJ9", Name = "Dominican Republic", Latitude = 18.735693, Longitude = -70.16265099999998 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 681, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 682, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 683, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 684, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 685, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 687, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 688, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 689, PlaceId = "ChIJr", Name = "Soluciones GBH, Avenida Ingeniero Roberto Pastoriza, Santo Domingo, República Dominicana", Latitude = 18.472236, Longitude = -69.92275319999999 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 690, PlaceId = "ChIJr", Name = "Soluciones GBH, Avenida Ingeniero Roberto Pastoriza, Santo Domingo, República Dominicana", Latitude = 18.472236, Longitude = -69.92275319999999 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 691, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 692, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 693, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, República Dominicana", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 699, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 700, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, República Dominicana", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 702, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 703, PlaceId = "ChIJV", Name = "Santo Domingo Este, Dominican Republic", Latitude = 18.505583, Longitude = -69.80017620000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 704, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, República Dominicana", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 705, PlaceId = "ChIJn", Name = "Santiago De Los Caballeros, Dominican Republic", Latitude = 19.4791963, Longitude = -70.69305680000002 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 706, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 707, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 708, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 709, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 710, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 711, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 712, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 713, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 714, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 715, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 716, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 717, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 718, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 719, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 720, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 721, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 722, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 723, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 724, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 725, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 726, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 727, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 728, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 729, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 730, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 731, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 732, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 733, PlaceId = "ChIJV", Name = "Santo Domingo Este, Dominican Republic", Latitude = 18.505583, Longitude = -69.80017620000001 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 734, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 735, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 736, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 737, PlaceId = "ChIJq", Name = "Santo Domingo, Доминиканская Республика", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 738, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 739, PlaceId = "ChIJx", Name = "Ensanche Piantini, Santo Domingo, Dominican Republic", Latitude = 18.4738025, Longitude = -69.93567840000003 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 740, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 741, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 742, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 743, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 744, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 745, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 746, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 747, PlaceId = "ChIJq", Name = "Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 748, PlaceId = "ChIJ9", Name = "Distrito Nacional, Santo Domingo, Dominican Republic", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 749, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
            Insert.IntoTable(TableName.Location).Row(new Location { Id = 750, PlaceId = "ChIJq", Name = "Santo Domingo, República Dominicana", Latitude = 18.48605749999999, Longitude = -69.9312117 });
        }
    }
}
